name: Build and Release (Nightly)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-release:
    uses: './.github/workflows/build.yml'
    with:
      build_type: 'release'

  build-debug:
    uses: './.github/workflows/build.yml'
    with:
      build_type: 'debug'
  
  release:
    runs-on: ubuntu-latest
    needs: [build-release, build-debug]
    if: always() && !contains(needs.*.result, 'cancelled')
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: 'niobium-*'
        merge-multiple: true

    - name: 'Release'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: 'nightly'
        files: |
          *.tar.gz